---
title: "text entry, plots"
output: 
  html_document:
    theme: cosmo
editor_options:
  chunk_output_type: inline
date: "2023-08-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
library(readr)
library(tidyverse)
library(gtsummary)
library(Rmisc)
library(scales)
library(data.table)
library(cowplot)
library(gridExtra)
```

```{r}
# dataset resulted from the analysis in main_analysis.ipynb doc
df = read_csv("/data/df_full_filtered.csv")
```

```{r}
# double check of analysis

library(afex)
library(gtsummary)

aov_interaction <- aov_car(wpm ~ keyboard * block + Error(identifier/(keyboard * block)), data = df)
summary(aov_interaction)
```

### typing speed plot

```{r}
df |> select(block, keyboard, wpm)

linedata <- df %>%
dplyr::group_by(block, keyboard) %>%
dplyr::summarise(mean_wpm = mean(wpm), ci = 1.96 * sd(wpm) / sqrt(n()), mean_cer = mean(cer), ci_cer = 1.96 * sd(cer) / sqrt(n()), .groups = "drop")


p = ggplot(data=linedata, aes(x=block, y=mean_wpm, group=keyboard, colour=keyboard)) +
  geom_line(size = 0.75) +
  geom_errorbar(aes(ymin=mean_wpm-ci, ymax=mean_wpm+ci), width=0.05, alpha=0.65, size=0.75) +
  geom_point(size = 2) +
  scale_color_manual(values = c(alpha("#00AFBB", 0.75), alpha("#E7B800", 0.5)), labels = c("Baseline", "Cognitive")) + # Capitalize the legend labels here
  theme_classic() +
  theme(
    panel.grid.major = element_line(colour = "#dddddd", size=0.4),
    panel.grid.major.x = element_line(colour = "#dddddd", linetype="dashed", size=0.25),
    legend.title = element_blank(),
    legend.position = "bottom",
    legend.justification = "center",
    legend.margin = margin(0,0,0,0),
    legend.box.margin = margin(-5,-5,-5,-5),
    plot.margin = unit(c(0.1,0.1,0.1,0.1), "cm"),
    axis.ticks = element_line(size = .5, colour = "black"),
    plot.title = element_text(size = 20)
  ) +
  guides(colour = guide_legend(override.aes = list(shape = NA, size = 0.75))) + # Match the line size in the legend
  labs(title = "", x = "Block", y = "Mean typing speed (WPM)") +
  scale_y_continuous(limits = c(9, 13), expand = c(0, 0)) + guides(color = FALSE) 


# Print the ggplot object
print(p)

# Save the plot to a PDF
pdf("/figures/wpm.pdf", width = 4, height = 3)
print(p)  # Print it again within the pdf() function
dev.off()
```

### character error rate plot

```{r}
p = ggplot(data=linedata, aes(x=block, y=mean_cer, group=keyboard, colour=keyboard)) +
  geom_line(size = 0.75) +
  geom_errorbar(aes(ymin=mean_cer-ci_cer, ymax=mean_cer+ci_cer), width=0.05, alpha=0.65, size=0.75) +
  geom_point(size = 2) +
  scale_color_manual(values = c(alpha("#00AFBB", 0.75), alpha("#E7B800", 0.5)), labels = c("Baseline", "Cognitive")) + # Capitalize the legend labels here
  theme_classic() +
  theme(
    panel.grid.major = element_line(colour = "#dddddd", size=0.4),
    panel.grid.major.x = element_line(colour = "#dddddd", linetype="dashed", size=0.25),
    legend.title = element_blank(),
    legend.position = "bottom",
    legend.justification = "center",
    legend.margin = margin(0,0,0,0),
    legend.box.margin = margin(-5,-5,-5,-5),
    plot.margin = unit(c(0.1,0.1,0.1,0.1), "cm"),
    axis.ticks = element_line(size = .5, colour = "black"),
    plot.title = element_text(size = 20)
  ) +
  guides(colour = guide_legend(override.aes = list(shape = NA, size = 0.75))) + # Match the line size in the legend
  labs(title = "", x = "Block", y = "Character error rate (CER)") + 
  scale_y_continuous(limits = c(0, 0.05), expand = c(0, 0)) + guides(color = FALSE) 

# Print the ggplot object
print(p)

# Save the plot to a PDF
pdf("/figures/cer.pdf", width = 4, height = 3)
print(p)  # Print it again within the pdf() function
dev.off()
```

### legend extraction

```{r}
main_plot <- ggplot(data=linedata, aes(x=block, y=mean_wpm, group=keyboard, colour=keyboard)) +
  geom_line(size = 0.75) +
  geom_errorbar(aes(ymin=mean_wpm-ci, ymax=mean_wpm+ci), width=0.05, alpha=0.65, size=0.75) +
  geom_point(size = 2) +
  scale_color_manual(values = c(alpha("#00AFBB", 0.75), alpha("#E7B800", 0.5)), labels = c("Baseline", "Cognitive")) + # Capitalize the legend labels here
  theme_classic() +
  theme(
    panel.grid.major = element_line(colour = "#dddddd", size=0.4),
    panel.grid.major.x = element_line(colour = "#dddddd", linetype="dashed", size=0.25),
    legend.title = element_blank(),
    legend.position = "bottom",
    legend.justification = "center",
    legend.margin = margin(0,0,0,0),
    legend.box.margin = margin(-5,-5,-5,-5),
    plot.margin = unit(c(0.1,0.1,0.1,0.1), "cm"),
    axis.ticks = element_line(size = .5, colour = "black"),
    plot.title = element_text(size = 20)
  ) +
  guides(colour = guide_legend(override.aes = list(shape = NA, size = 0.75))) + # Match the line size in the legend
  labs(title = "", x = "Block", y = "Mean typing speed (WPM)") +
  scale_y_continuous(limits = c(9, 13), expand = c(0, 0))

# Create a separate legend plot
legend_plot <- get_legend(main_plot)
grid.arrange(legend_plot, ncol = 1)

pdf('/figures/legend_plot.pdf')
grid.arrange(legend_plot, ncol = 1)  # Print it again within the pdf() function
dev.off()
```